document:
  name: SPID/CIE OpenID Connect Regole tecniche
  description: |
    Regole tecniche OpenID Connect per i sistemi nazionali di Identità Digitale SPID e CIE id.
  tags:
    - standard 
    - interoperabilità
    - spid
    - cie
    - oidc
    - openid
  
